//
//Copyright 2021 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.4
// source: dapr/proto/runtime/v1/appcallback.proto

package runtime

import (
	context "context"
	v1 "github.com/dapr/dapr/pkg/proto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AppCallback_OnInvoke_FullMethodName               = "/dapr.proto.runtime.v1.AppCallback/OnInvoke"
	AppCallback_ListTopicSubscriptions_FullMethodName = "/dapr.proto.runtime.v1.AppCallback/ListTopicSubscriptions"
	AppCallback_OnTopicEvent_FullMethodName           = "/dapr.proto.runtime.v1.AppCallback/OnTopicEvent"
	AppCallback_ListInputBindings_FullMethodName      = "/dapr.proto.runtime.v1.AppCallback/ListInputBindings"
	AppCallback_OnBindingEvent_FullMethodName         = "/dapr.proto.runtime.v1.AppCallback/OnBindingEvent"
	AppCallback_OnBulkTopicEvent_FullMethodName       = "/dapr.proto.runtime.v1.AppCallback/OnBulkTopicEvent"
)

// AppCallbackClient is the client API for AppCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppCallbackClient interface {
	// Invokes service method with InvokeRequest.
	OnInvoke(ctx context.Context, in *v1.InvokeRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error)
	// Lists all topics subscribed by this app.
	ListTopicSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicSubscriptionsResponse, error)
	// Subscribes events from Pubsub
	OnTopicEvent(ctx context.Context, in *TopicEventRequest, opts ...grpc.CallOption) (*TopicEventResponse, error)
	// Lists all input bindings subscribed by this app.
	ListInputBindings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListInputBindingsResponse, error)
	// Listens events from the input bindings
	//
	// User application can save the states or send the events to the output
	// bindings optionally by returning BindingEventResponse.
	OnBindingEvent(ctx context.Context, in *BindingEventRequest, opts ...grpc.CallOption) (*BindingEventResponse, error)
	// Subscribes bulk events from Pubsub
	OnBulkTopicEvent(ctx context.Context, in *TopicEventBulkRequest, opts ...grpc.CallOption) (*TopicEventBulkResponse, error)
}

type appCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewAppCallbackClient(cc grpc.ClientConnInterface) AppCallbackClient {
	return &appCallbackClient{cc}
}

func (c *appCallbackClient) OnInvoke(ctx context.Context, in *v1.InvokeRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error) {
	out := new(v1.InvokeResponse)
	err := c.cc.Invoke(ctx, AppCallback_OnInvoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) ListTopicSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicSubscriptionsResponse, error) {
	out := new(ListTopicSubscriptionsResponse)
	err := c.cc.Invoke(ctx, AppCallback_ListTopicSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) OnTopicEvent(ctx context.Context, in *TopicEventRequest, opts ...grpc.CallOption) (*TopicEventResponse, error) {
	out := new(TopicEventResponse)
	err := c.cc.Invoke(ctx, AppCallback_OnTopicEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) ListInputBindings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListInputBindingsResponse, error) {
	out := new(ListInputBindingsResponse)
	err := c.cc.Invoke(ctx, AppCallback_ListInputBindings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) OnBindingEvent(ctx context.Context, in *BindingEventRequest, opts ...grpc.CallOption) (*BindingEventResponse, error) {
	out := new(BindingEventResponse)
	err := c.cc.Invoke(ctx, AppCallback_OnBindingEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackClient) OnBulkTopicEvent(ctx context.Context, in *TopicEventBulkRequest, opts ...grpc.CallOption) (*TopicEventBulkResponse, error) {
	out := new(TopicEventBulkResponse)
	err := c.cc.Invoke(ctx, AppCallback_OnBulkTopicEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppCallbackServer is the server API for AppCallback service.
// All implementations should embed UnimplementedAppCallbackServer
// for forward compatibility
type AppCallbackServer interface {
	// Invokes service method with InvokeRequest.
	OnInvoke(context.Context, *v1.InvokeRequest) (*v1.InvokeResponse, error)
	// Lists all topics subscribed by this app.
	ListTopicSubscriptions(context.Context, *emptypb.Empty) (*ListTopicSubscriptionsResponse, error)
	// Subscribes events from Pubsub
	OnTopicEvent(context.Context, *TopicEventRequest) (*TopicEventResponse, error)
	// Lists all input bindings subscribed by this app.
	ListInputBindings(context.Context, *emptypb.Empty) (*ListInputBindingsResponse, error)
	// Listens events from the input bindings
	//
	// User application can save the states or send the events to the output
	// bindings optionally by returning BindingEventResponse.
	OnBindingEvent(context.Context, *BindingEventRequest) (*BindingEventResponse, error)
	// Subscribes bulk events from Pubsub
	OnBulkTopicEvent(context.Context, *TopicEventBulkRequest) (*TopicEventBulkResponse, error)
}

// UnimplementedAppCallbackServer should be embedded to have forward compatible implementations.
type UnimplementedAppCallbackServer struct {
}

func (UnimplementedAppCallbackServer) OnInvoke(context.Context, *v1.InvokeRequest) (*v1.InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnInvoke not implemented")
}
func (UnimplementedAppCallbackServer) ListTopicSubscriptions(context.Context, *emptypb.Empty) (*ListTopicSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopicSubscriptions not implemented")
}
func (UnimplementedAppCallbackServer) OnTopicEvent(context.Context, *TopicEventRequest) (*TopicEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTopicEvent not implemented")
}
func (UnimplementedAppCallbackServer) ListInputBindings(context.Context, *emptypb.Empty) (*ListInputBindingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInputBindings not implemented")
}
func (UnimplementedAppCallbackServer) OnBindingEvent(context.Context, *BindingEventRequest) (*BindingEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBindingEvent not implemented")
}
func (UnimplementedAppCallbackServer) OnBulkTopicEvent(context.Context, *TopicEventBulkRequest) (*TopicEventBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBulkTopicEvent not implemented")
}

// UnsafeAppCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppCallbackServer will
// result in compilation errors.
type UnsafeAppCallbackServer interface {
	mustEmbedUnimplementedAppCallbackServer()
}

func RegisterAppCallbackServer(s grpc.ServiceRegistrar, srv AppCallbackServer) {
	s.RegisterService(&AppCallback_ServiceDesc, srv)
}

func _AppCallback_OnInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_OnInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnInvoke(ctx, req.(*v1.InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_ListTopicSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).ListTopicSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_ListTopicSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).ListTopicSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_OnTopicEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnTopicEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_OnTopicEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnTopicEvent(ctx, req.(*TopicEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_ListInputBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).ListInputBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_ListInputBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).ListInputBindings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_OnBindingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnBindingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_OnBindingEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnBindingEvent(ctx, req.(*BindingEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallback_OnBulkTopicEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicEventBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackServer).OnBulkTopicEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallback_OnBulkTopicEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackServer).OnBulkTopicEvent(ctx, req.(*TopicEventBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppCallback_ServiceDesc is the grpc.ServiceDesc for AppCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.AppCallback",
	HandlerType: (*AppCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnInvoke",
			Handler:    _AppCallback_OnInvoke_Handler,
		},
		{
			MethodName: "ListTopicSubscriptions",
			Handler:    _AppCallback_ListTopicSubscriptions_Handler,
		},
		{
			MethodName: "OnTopicEvent",
			Handler:    _AppCallback_OnTopicEvent_Handler,
		},
		{
			MethodName: "ListInputBindings",
			Handler:    _AppCallback_ListInputBindings_Handler,
		},
		{
			MethodName: "OnBindingEvent",
			Handler:    _AppCallback_OnBindingEvent_Handler,
		},
		{
			MethodName: "OnBulkTopicEvent",
			Handler:    _AppCallback_OnBulkTopicEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/appcallback.proto",
}

const (
	AppCallbackHealthCheck_HealthCheck_FullMethodName = "/dapr.proto.runtime.v1.AppCallbackHealthCheck/HealthCheck"
)

// AppCallbackHealthCheckClient is the client API for AppCallbackHealthCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppCallbackHealthCheckClient interface {
	// Health check.
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type appCallbackHealthCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewAppCallbackHealthCheckClient(cc grpc.ClientConnInterface) AppCallbackHealthCheckClient {
	return &appCallbackHealthCheckClient{cc}
}

func (c *appCallbackHealthCheckClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AppCallbackHealthCheck_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppCallbackHealthCheckServer is the server API for AppCallbackHealthCheck service.
// All implementations should embed UnimplementedAppCallbackHealthCheckServer
// for forward compatibility
type AppCallbackHealthCheckServer interface {
	// Health check.
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
}

// UnimplementedAppCallbackHealthCheckServer should be embedded to have forward compatible implementations.
type UnimplementedAppCallbackHealthCheckServer struct {
}

func (UnimplementedAppCallbackHealthCheckServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

// UnsafeAppCallbackHealthCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppCallbackHealthCheckServer will
// result in compilation errors.
type UnsafeAppCallbackHealthCheckServer interface {
	mustEmbedUnimplementedAppCallbackHealthCheckServer()
}

func RegisterAppCallbackHealthCheckServer(s grpc.ServiceRegistrar, srv AppCallbackHealthCheckServer) {
	s.RegisterService(&AppCallbackHealthCheck_ServiceDesc, srv)
}

func _AppCallbackHealthCheck_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackHealthCheckServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackHealthCheck_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackHealthCheckServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AppCallbackHealthCheck_ServiceDesc is the grpc.ServiceDesc for AppCallbackHealthCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppCallbackHealthCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.AppCallbackHealthCheck",
	HandlerType: (*AppCallbackHealthCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AppCallbackHealthCheck_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/appcallback.proto",
}

const (
	AppCallbackAlpha_OnBulkTopicEventAlpha1_FullMethodName = "/dapr.proto.runtime.v1.AppCallbackAlpha/OnBulkTopicEventAlpha1"
	AppCallbackAlpha_OnJobEventAlpha1_FullMethodName       = "/dapr.proto.runtime.v1.AppCallbackAlpha/OnJobEventAlpha1"
)

// AppCallbackAlphaClient is the client API for AppCallbackAlpha service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppCallbackAlphaClient interface {
	// Deprecated: Do not use.
	// Subscribes bulk events from Pubsub
	OnBulkTopicEventAlpha1(ctx context.Context, in *TopicEventBulkRequest, opts ...grpc.CallOption) (*TopicEventBulkResponse, error)
	// Sends job back to the app's endpoint at trigger time.
	OnJobEventAlpha1(ctx context.Context, in *JobEventRequest, opts ...grpc.CallOption) (*JobEventResponse, error)
}

type appCallbackAlphaClient struct {
	cc grpc.ClientConnInterface
}

func NewAppCallbackAlphaClient(cc grpc.ClientConnInterface) AppCallbackAlphaClient {
	return &appCallbackAlphaClient{cc}
}

// Deprecated: Do not use.
func (c *appCallbackAlphaClient) OnBulkTopicEventAlpha1(ctx context.Context, in *TopicEventBulkRequest, opts ...grpc.CallOption) (*TopicEventBulkResponse, error) {
	out := new(TopicEventBulkResponse)
	err := c.cc.Invoke(ctx, AppCallbackAlpha_OnBulkTopicEventAlpha1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackAlphaClient) OnJobEventAlpha1(ctx context.Context, in *JobEventRequest, opts ...grpc.CallOption) (*JobEventResponse, error) {
	out := new(JobEventResponse)
	err := c.cc.Invoke(ctx, AppCallbackAlpha_OnJobEventAlpha1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppCallbackAlphaServer is the server API for AppCallbackAlpha service.
// All implementations should embed UnimplementedAppCallbackAlphaServer
// for forward compatibility
type AppCallbackAlphaServer interface {
	// Deprecated: Do not use.
	// Subscribes bulk events from Pubsub
	OnBulkTopicEventAlpha1(context.Context, *TopicEventBulkRequest) (*TopicEventBulkResponse, error)
	// Sends job back to the app's endpoint at trigger time.
	OnJobEventAlpha1(context.Context, *JobEventRequest) (*JobEventResponse, error)
}

// UnimplementedAppCallbackAlphaServer should be embedded to have forward compatible implementations.
type UnimplementedAppCallbackAlphaServer struct {
}

func (UnimplementedAppCallbackAlphaServer) OnBulkTopicEventAlpha1(context.Context, *TopicEventBulkRequest) (*TopicEventBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBulkTopicEventAlpha1 not implemented")
}
func (UnimplementedAppCallbackAlphaServer) OnJobEventAlpha1(context.Context, *JobEventRequest) (*JobEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnJobEventAlpha1 not implemented")
}

// UnsafeAppCallbackAlphaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppCallbackAlphaServer will
// result in compilation errors.
type UnsafeAppCallbackAlphaServer interface {
	mustEmbedUnimplementedAppCallbackAlphaServer()
}

func RegisterAppCallbackAlphaServer(s grpc.ServiceRegistrar, srv AppCallbackAlphaServer) {
	s.RegisterService(&AppCallbackAlpha_ServiceDesc, srv)
}

func _AppCallbackAlpha_OnBulkTopicEventAlpha1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicEventBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackAlphaServer).OnBulkTopicEventAlpha1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackAlpha_OnBulkTopicEventAlpha1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackAlphaServer).OnBulkTopicEventAlpha1(ctx, req.(*TopicEventBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackAlpha_OnJobEventAlpha1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackAlphaServer).OnJobEventAlpha1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackAlpha_OnJobEventAlpha1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackAlphaServer).OnJobEventAlpha1(ctx, req.(*JobEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppCallbackAlpha_ServiceDesc is the grpc.ServiceDesc for AppCallbackAlpha service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppCallbackAlpha_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.AppCallbackAlpha",
	HandlerType: (*AppCallbackAlphaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnBulkTopicEventAlpha1",
			Handler:    _AppCallbackAlpha_OnBulkTopicEventAlpha1_Handler,
		},
		{
			MethodName: "OnJobEventAlpha1",
			Handler:    _AppCallbackAlpha_OnJobEventAlpha1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/appcallback.proto",
}

const (
	AppCallbackActors_GetRegisteredActors_FullMethodName = "/dapr.proto.runtime.v1.AppCallbackActors/GetRegisteredActors"
	AppCallbackActors_OnActorActivate_FullMethodName     = "/dapr.proto.runtime.v1.AppCallbackActors/OnActorActivate"
	AppCallbackActors_OnActorDeactivate_FullMethodName   = "/dapr.proto.runtime.v1.AppCallbackActors/OnActorDeactivate"
	AppCallbackActors_OnActorInvoke_FullMethodName       = "/dapr.proto.runtime.v1.AppCallbackActors/OnActorInvoke"
	AppCallbackActors_OnActorReminder_FullMethodName     = "/dapr.proto.runtime.v1.AppCallbackActors/OnActorReminder"
	AppCallbackActors_OnActorTimer_FullMethodName        = "/dapr.proto.runtime.v1.AppCallbackActors/OnActorTimer"
)

// AppCallbackActorsClient is the client API for AppCallbackActors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppCallbackActorsClient interface {
	// GetRegisteredActors returns the actor types the app hosts together with
	// per-type runtime configuration.
	GetRegisteredActors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RegisteredActorsResponse, error)
	// OnActorActivate is invoked when Dapr activates a new actor instance on
	// this host.
	OnActorActivate(ctx context.Context, in *ActivateActorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// OnActorDeactivate is invoked when Dapr deactivates an actor instance.
	OnActorDeactivate(ctx context.Context, in *DeactivateActorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// OnActorInvoke invokes a method on an actor hosted by this app.
	OnActorInvoke(ctx context.Context, in *OnActorInvokeRequest, opts ...grpc.CallOption) (*OnActorInvokeResponse, error)
	// OnActorReminder fires a reminder on an actor hosted by this app.
	OnActorReminder(ctx context.Context, in *OnActorReminderRequest, opts ...grpc.CallOption) (*OnActorReminderResponse, error)
	// OnActorTimer fires a timer on an actor hosted by this app.
	OnActorTimer(ctx context.Context, in *OnActorTimerRequest, opts ...grpc.CallOption) (*OnActorReminderResponse, error)
}

type appCallbackActorsClient struct {
	cc grpc.ClientConnInterface
}

func NewAppCallbackActorsClient(cc grpc.ClientConnInterface) AppCallbackActorsClient {
	return &appCallbackActorsClient{cc}
}

func (c *appCallbackActorsClient) GetRegisteredActors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RegisteredActorsResponse, error) {
	out := new(RegisteredActorsResponse)
	err := c.cc.Invoke(ctx, AppCallbackActors_GetRegisteredActors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackActorsClient) OnActorActivate(ctx context.Context, in *ActivateActorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppCallbackActors_OnActorActivate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackActorsClient) OnActorDeactivate(ctx context.Context, in *DeactivateActorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AppCallbackActors_OnActorDeactivate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackActorsClient) OnActorInvoke(ctx context.Context, in *OnActorInvokeRequest, opts ...grpc.CallOption) (*OnActorInvokeResponse, error) {
	out := new(OnActorInvokeResponse)
	err := c.cc.Invoke(ctx, AppCallbackActors_OnActorInvoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackActorsClient) OnActorReminder(ctx context.Context, in *OnActorReminderRequest, opts ...grpc.CallOption) (*OnActorReminderResponse, error) {
	out := new(OnActorReminderResponse)
	err := c.cc.Invoke(ctx, AppCallbackActors_OnActorReminder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appCallbackActorsClient) OnActorTimer(ctx context.Context, in *OnActorTimerRequest, opts ...grpc.CallOption) (*OnActorReminderResponse, error) {
	out := new(OnActorReminderResponse)
	err := c.cc.Invoke(ctx, AppCallbackActors_OnActorTimer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppCallbackActorsServer is the server API for AppCallbackActors service.
// All implementations should embed UnimplementedAppCallbackActorsServer
// for forward compatibility
type AppCallbackActorsServer interface {
	// GetRegisteredActors returns the actor types the app hosts together with
	// per-type runtime configuration.
	GetRegisteredActors(context.Context, *emptypb.Empty) (*RegisteredActorsResponse, error)
	// OnActorActivate is invoked when Dapr activates a new actor instance on
	// this host.
	OnActorActivate(context.Context, *ActivateActorRequest) (*emptypb.Empty, error)
	// OnActorDeactivate is invoked when Dapr deactivates an actor instance.
	OnActorDeactivate(context.Context, *DeactivateActorRequest) (*emptypb.Empty, error)
	// OnActorInvoke invokes a method on an actor hosted by this app.
	OnActorInvoke(context.Context, *OnActorInvokeRequest) (*OnActorInvokeResponse, error)
	// OnActorReminder fires a reminder on an actor hosted by this app.
	OnActorReminder(context.Context, *OnActorReminderRequest) (*OnActorReminderResponse, error)
	// OnActorTimer fires a timer on an actor hosted by this app.
	OnActorTimer(context.Context, *OnActorTimerRequest) (*OnActorReminderResponse, error)
}

// UnimplementedAppCallbackActorsServer should be embedded to have forward compatible implementations.
type UnimplementedAppCallbackActorsServer struct {
}

func (UnimplementedAppCallbackActorsServer) GetRegisteredActors(context.Context, *emptypb.Empty) (*RegisteredActorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredActors not implemented")
}
func (UnimplementedAppCallbackActorsServer) OnActorActivate(context.Context, *ActivateActorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnActorActivate not implemented")
}
func (UnimplementedAppCallbackActorsServer) OnActorDeactivate(context.Context, *DeactivateActorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnActorDeactivate not implemented")
}
func (UnimplementedAppCallbackActorsServer) OnActorInvoke(context.Context, *OnActorInvokeRequest) (*OnActorInvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnActorInvoke not implemented")
}
func (UnimplementedAppCallbackActorsServer) OnActorReminder(context.Context, *OnActorReminderRequest) (*OnActorReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnActorReminder not implemented")
}
func (UnimplementedAppCallbackActorsServer) OnActorTimer(context.Context, *OnActorTimerRequest) (*OnActorReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnActorTimer not implemented")
}

// UnsafeAppCallbackActorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppCallbackActorsServer will
// result in compilation errors.
type UnsafeAppCallbackActorsServer interface {
	mustEmbedUnimplementedAppCallbackActorsServer()
}

func RegisterAppCallbackActorsServer(s grpc.ServiceRegistrar, srv AppCallbackActorsServer) {
	s.RegisterService(&AppCallbackActors_ServiceDesc, srv)
}

func _AppCallbackActors_GetRegisteredActors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).GetRegisteredActors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_GetRegisteredActors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).GetRegisteredActors(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackActors_OnActorActivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).OnActorActivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_OnActorActivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).OnActorActivate(ctx, req.(*ActivateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackActors_OnActorDeactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).OnActorDeactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_OnActorDeactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).OnActorDeactivate(ctx, req.(*DeactivateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackActors_OnActorInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnActorInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).OnActorInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_OnActorInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).OnActorInvoke(ctx, req.(*OnActorInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackActors_OnActorReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnActorReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).OnActorReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_OnActorReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).OnActorReminder(ctx, req.(*OnActorReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppCallbackActors_OnActorTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnActorTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppCallbackActorsServer).OnActorTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppCallbackActors_OnActorTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppCallbackActorsServer).OnActorTimer(ctx, req.(*OnActorTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppCallbackActors_ServiceDesc is the grpc.ServiceDesc for AppCallbackActors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppCallbackActors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.AppCallbackActors",
	HandlerType: (*AppCallbackActorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegisteredActors",
			Handler:    _AppCallbackActors_GetRegisteredActors_Handler,
		},
		{
			MethodName: "OnActorActivate",
			Handler:    _AppCallbackActors_OnActorActivate_Handler,
		},
		{
			MethodName: "OnActorDeactivate",
			Handler:    _AppCallbackActors_OnActorDeactivate_Handler,
		},
		{
			MethodName: "OnActorInvoke",
			Handler:    _AppCallbackActors_OnActorInvoke_Handler,
		},
		{
			MethodName: "OnActorReminder",
			Handler:    _AppCallbackActors_OnActorReminder_Handler,
		},
		{
			MethodName: "OnActorTimer",
			Handler:    _AppCallbackActors_OnActorTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/appcallback.proto",
}
